feat: 📢 Add Opportunities path
valory-xyz/autonolas-build-frontend pull request #7
Opened 2024-04-17 18:09 UTC by mohandast52

https://github.com/valory-xyz/autonolas-build-frontend/assets/22061815/582a084c-b563-428d-9960-2b543faf37ad

2024-04-17 19:31 UTC, truemiller submitted a review, later dismissed

2024-04-18 09:00 UTC, oaksprout requested changes

2024-04-18 09:00 UTC, oaksprout commented on public/paths-markdown/ecosystem-opportunities.md
> +*Requires that somebody with at least 10k veOLAS donates to a service that uses your code.
```suggestion
*Requires that you mint your code and that somebody with at least 10k veOLAS donates to a service that uses your code.
```

2024-04-18 09:58 UTC, DavidMinarsch approved these changes

2024-04-18 10:23 UTC, truemiller approved these changes

2024-04-18 10:35 UTC, oaksprout approved these changes

2024-04-18 10:35 UTC, merged